apiVersion: extensions/v1beta1
kind: Ingress
metadata:
#  annotations:
#    field.cattle.io/publicEndpoints: '[{"addresses":[""],"port":443,"protocol":"HTTPS",
#    "serviceName":"omar-dev:omar-lite-wms","ingressName":"omar-dev:omar-lite-wms","hostname":"omar-lite-wms.ossim.io","path":"/",
#    "allNodes":false}]'
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
spec:
  rules:
  - host: {{ .Values.global.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Chart.Name }}
          servicePort: 8080
        path: /
  tls:
  - hosts:
    - {{ .Values.global.ingress.host }}
    secretName: ssl-certs
status:
  loadBalancer:
    ingress:
    - hostname: {{ .Values.global.ingress.loadBalancer }}